# Build stage
FROM maven:3.9.6-eclipse-temurin-17-alpine AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn package -DskipTests

# Runtime stage
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
RUN mkdir -p /app/db
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENV SPRING_DATASOURCE_URL=jdbc:sqlite:/app/db/oficina.db
ENV SPRING_SQL_INIT_MODE=never

ENTRYPOINT ["java", "-jar", "app.jar"]
